# Generated by Django 5.1.7 on 2025-03-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.ImageField(default='sori_snow_boy.png', upload_to='user_icons', verbose_name='画像'),
        ),
    ]
